import type { PullRequest, PullRequestFile } from "./github.js";

const NIM_BASE = "https://integrate.api.nvidia.com/v1";

export async function summarizePR(
  pr: PullRequest,
  files: PullRequestFile[],
  diff: string,
  apiKey: string,
  model = "nvidia/nemotron-3-ultra-550b-a55b"
): Promise<string> {
  const fileList = files.map(f => `${f.status}: ${f.filename} (+${f.additions}/-${f.deletions})`).join("\n");
  const labels = pr.labels.map(l => l.name).join(", ") || "none";

  const prompt = `You are a senior code reviewer writing a concise, informative pull request summary for a team.

Pull Request: #${pr.number} — ${pr.title}
Author: ${pr.user.login}
Base → Head: ${pr.base.ref} → ${pr.head.ref}
Labels: ${labels}
Draft: ${pr.draft}
Stats: +${pr.additions} lines, -${pr.deletions} lines, ${pr.changed_files} files changed

PR Description:
${pr.body || "(no description provided)"}

Files changed:
${fileList}

Diff sample:
${diff}

Write a PR summary with these exact sections:

## 📋 What Changed
2-4 sentences describing what this PR does in plain English.

## 🎯 Why It Matters
1-3 sentences on the business or technical motivation.

## ⚠️ Potential Risks
Bullet list of anything that could break, regress, or needs careful testing. Be specific. If none, say "No significant risks identified."

## ✅ What to Test
Bullet list of specific things a reviewer should test or verify.

## 📁 Key Files
List the most important files changed and briefly explain what changed in each.

Be precise, technical, and concise. Use markdown formatting. Do not pad with filler text.`;

  const resp = await fetch(`${NIM_BASE}/chat/completions`, {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({ model, messages: [{ role: "user", content: prompt }], temperature: 0.2, max_tokens: 1500 }),
  });

  if (!resp.ok) {
    const body = await resp.text().catch(() => "");
    throw new Error(`NIM API error ${resp.status}: ${body}`);
  }

  const data = await resp.json() as { choices: Array<{ message: { content: string } }> };
  return data.choices[0]?.message.content ?? "";
}

export function wrapComment(summary: string, prNumber: number, model: string): string {
  const now = new Date().toUTCString();
  return `<!-- pr-brief-comment -->
${summary}

---
<sub>Generated by [pr-brief](https://github.com/yourusername/pr-brief) using \`${model}\` • ${now} • [Re-run](?)</sub>`;
}

export const AVAILABLE_MODELS = [
  "nvidia/nemotron-3-ultra-550b-a55b",
  "meta/llama-3.3-70b-instruct",
  "mistralai/mistral-large-2-instruct",
  "qwen/qwen2.5-72b-instruct",
] as const;

export type AvailableModel = typeof AVAILABLE_MODELS[number];

export const AVAILABLE_MODELS = [
  "nvidia/nemotron-3-ultra-550b-a55b",
  "meta/llama-3.3-70b-instruct",
  "mistralai/mistral-large-2-instruct",
  "qwen/qwen2.5-72b-instruct",
] as const;

export type AvailableModel = typeof AVAILABLE_MODELS[number];
